### ISSUE TITLE
Readme has broken URL "Connect Azure Sphere to Ethernet"

### ISSUE THREAD

**Issue by ccassidy-ms** [Azure/azure-sphere-samples#103]
In the readme for the Private Network Services sample, the URL link for "Connect Azure Sphere to Ethernet" is broken.

Currently it is set to:

https://docs.microsoft.com/azure-sphere/network/connect-private-network

It should be the following:

https://docs.microsoft.com/azure-sphere/network/connect-ethernet

**Comment by richardtaylorrt** [comment]
Hi - thanks for raising.  This should be fixed now.
