### ISSUE TITLE
GpioBlock addresses for GPIO 43 and 1

### ISSUE THREAD

**Issue by bluetiger9** [Azure/azure-sphere-samples#107]
Hi,

I would like to use **GPIO 43** and **GPIO 1** from the **RT cores** on the [**Avnet's Azure Sphere Kit (AES-MS-MT3620-SK-G)**](https://www.avnet.com/shop/us/products/avnet-engineering-services/aes-ms-mt3620-sk-g-3074457345636825680/). These are the AN an the PWM pins from Click interface nr. 2.

I'm using the [**GPIO_RTApp_MT3620_BareMetal** example](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/GPIO/GPIO_RTApp_MT3620_BareMetal) as a base.

Before using a GPIO pin, a **`GpioBlock`** like the bellow one must be defined and added:
```
    // Block includes led1RedGpio, GPIO8.
    static const GpioBlock pwm2 = {
        .baseAddr = 0x38030000, .type = GpioBlock_PWM, .firstPin = 8, .pinCount = 4};

    Mt3620_Gpio_AddBlock(&pwm2);
```
Now, the example contains the **GpioBlock** definition for the **PWM 2** *(GPIO 8-11)* and **GPR 1** *(GPIO 12-15)* blocks, but **there is no info for the other GPIO blocks**.

**GPIO 1** shares the pin with **PWM 1**, which belongs to the PWM block 0. So, I think the it `GpioBlock` would be:
```
    static const GpioBlock pwm0 = {
        .baseAddr = 0x38010000, .type = GpioBlock_PWM, .firstPin = 0, .pinCount = 4};
```

But for **GPIO 43**, which shares the pin with **ADC2**, I found **NO information in the datasheets about what the `GpioBlock` addresses should be**:
```
    static const GpioBlock adc0 = {
        .baseAddr = 0x????????, .type = GpioBlock_ADC, .firstPin = 41, .pinCount = 48};
```

Can you help me figure this out?

_Note: I'm successfully used these GPIO-s from the high level application. So, I guess the information should be somewhere available, I just did not found it yet._

**Refs**:
- [**MT3620 M4 User Manual**](https://d86o2zu8ugzlg.cloudfront.net/mediatek-craft/documents/MT3620-M4-User-Manual.pdf)
- [**MT3620-Datasheet**](https://d86o2zu8ugzlg.cloudfront.net/mediatek-craft/documents/MT3620-Datasheet.pdf)

Thanks,
Attila

**Comment by richardtaylorrt** [comment]
Hi @bluetiger9 - Mediatek have recently published some additional samples for the MT3620 RT cores.  In particular, this [line ](https://github.com/MediaTek-Labs/mt3620_m4_software/blob/8ab192f55ba7ca04d56592dccd18e54f11918f84/MT3620_M4_Sample_Code/BareMetal/OS_HAL/src/os_hal_gpio.c#L41) suggests the base address you need is 0x38000000 .

Hope this helps.
