### ISSUE TITLE
Including library with CMake

### ISSUE THREAD

**Issue by josmithua** [Azure/azure-sphere-samples#113]
Hi there,

I've split my high level application up into 3 repositories/parts: the actual app and then two libraries (one for IoTHub stuff, one for graphics stuff). Both libraries are standalone, although they do rely on the Azure Sphere SDK (applibs, iothub functions, etc). I've gotten this to work without CMake, but now that things are moving towards CMake, I'm wondering how I can link the two libraries together with my main app using CMake. 

I think this is a common use case, so it would be helpful to have some instructions (and maybe a sample)

Cheers

**Comment by richardtaylorrt** [comment]
Hi - thanks for asking.  We'll look into whether there's an example we can show here.  In the meantime, I imagine that you'd have success with any general CMake advice online about working with static libraries.  For example, [here ](https://stackoverflow.com/questions/43772887/cmake-creating-a-static-library).  I've not yet tested myself, but I don't think there's anything Azure Sphere-specific that means this wouldn't work. Please let us know if that proves not to be the case.
