### ISSUE TITLE
README.md Has a Broken Link

### ISSUE THREAD

**Issue by msjsheridan** [Azure/azure-sphere-samples#118]
"Build and debug an RTApp from the command line." has a broken link to https://docs.microsoft.com/azure-sphere/app-development/rtapp-manual-build

**Comment by Jeff-Schafer** [comment]
Hi @msjsheridan:
Thank you for bring this to our attention.

We are currently tracking this.

**Comment by johnnyhli** [comment]
Hi @msjsheridan Thanks for your patience. We recently have new update for the Sample apps. This should be fixed now.
