### ISSUE TITLE
building application that use ethernet by VSCode is failed

### ISSUE THREAD

**Issue by atKeitaroTakahashi** [Azure/azure-sphere-samples#122]
I want to build Azure IoT sample application that use ethernet by VSCode.
Therefore, I used Networking_SetInterfaceState according to README. But CMake warned "implicit declaration of function".
I already write following words in app_manifest.json.
```
'"NetworkConfig": true, 
```
What should I do?

**Comment by richardtaylorrt** [comment]
Hi - Networking_SetInterfaceState is currently a Beta API.  Please see [here](Networking_SetInterfaceState) for how to target Beta APIs.

**Comment by atKeitaroTakahashi** [comment]
Oops, I have edited CMakeSettings.json until now. In VSCode, I Should have been edit .vscode/settings.json.
I was able to build, thank you!
