### ISSUE TITLE
ADC value is always maximum

### ISSUE THREAD

**Issue by matsujirushi** [Azure/azure-sphere-samples#126]
Maximum value is always displayed even if I change the potentiometer.
Code is [here](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/ADC/ADC_HighLevelApp).

```
The out sample value is 2.490 V
The out sample value is 2.493 V
The out sample value is 2.495 V
The out sample value is 2.498 V
The out sample value is 2.500 V
The out sample value is 2.483 V
The out sample value is 2.485 V
The out sample value is 2.488 V
The out sample value is 2.490 V
The out sample value is 2.493 V
The out sample value is 2.495 V
```

AzureSphereTargetApiSet is 4+Beta2001 and SDK is 20.01.

**Comment by johnnyhli** [comment]
Hi @matsujirushi – Can you share what hardware you were working on? If you are using MT3620 development kit, can you try a different ground pin? i.e. H1.2, H3.2, or H4.2 pin (please check [here ](https://docs.microsoft.com/en-us/azure-sphere/hardware/mt3620-user-guide#interface-headers)for more information). If you still have the issue, do you mind to share a diagram or a picture of your circuit?  If you want to share it privately, please sent to AzCommunity@microsoft.com with a link back to this issue. Thanks.

**Comment by matsujirushi** [comment]
Hardware connection is same [here](https://github.com/Azure/azure-sphere-samples/blob/master/Samples/ADC/ADC_HighLevelApp/README.md#set-up-the-adc-connections).

![image](https://user-images.githubusercontent.com/8079404/75772566-89185080-5d8f-11ea-82d0-a63571846150.png)

When cutting the blue wire and H2.11, center of potentiometer voltage is 1.25V.
But when the blue wire and H2.11 are connected, center of potentiometer voltage is 3.3V.
Looks like H2.11 is not an analog input.

**Comment by johnnyhli** [comment]
Hi @matsujirushi - I can't reproduce your case. Do you have another board that you can try?  Thanks.

**Comment by matsujirushi** [comment]
Hi,
I got another board and tested.
It's fine.

Maybe first rdb broken...

Thanks for your help.
