### ISSUE TITLE
Where to report issues with the sphere tooling?

### ISSUE THREAD

**Issue by JakeSays** [Azure/azure-sphere-samples#135]
I have found a critical issue with azsphere_slattach. Where do I go to open an issue? I'm asking here because it's all I can find.

**Comment by johnnyhli** [comment]
Hi @JakeSays - Thanks for reporting this issue. Are you using a Linux SDK? May I know which distro and which version you are using?  Thanks!

**Comment by johnnyhli** [comment]
Hi @JakeSays - Do you still have the issue? An updated Azure Sphere SDK for Linux, version 20.04 Update 1, is now available. Please follow the [installation instructions ](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk-linux)to download and install this updated SDK.

**Comment by JakeSays** [comment]
@johnnyhli I actually forgot I opened this. I had put my sphere work on the back burner, and am scheduled to get back to it sometime this week. At that point I'll check it out.

**Comment by johnnyhli** [comment]
Hi @JakeSays - Do you still have the issue? If not I'll closed this issue. Thanks.

**Comment by JakeSays** [comment]
@johnnyhli I haven't been able to reproduce it. I think it was related to upgrading my machine from ubuntu 19.10 to 20.04. It went away after I rebooted. It definitely was a bug but I doubt it'd ever occur under normal use.

**Comment by johnnyhli** [comment]
Hi @JakeSays - Thanks for the help to reproduce the bug. It should be fixed in 20.04 Update 1 SDK. I'll close this issue for now. If it ever occurs or if you have any questions related, please feel free reopen this issue. Thanks.
