### ISSUE TITLE
Improve document by inserting a picture 

### ISSUE THREAD

**Issue by xiongyu0523** [Azure/azure-sphere-samples#143]
In this [section](https://github.com/Azure/azure-sphere-samples/blob/master/Samples/AzureIoT/IoTCentral.md#configure-the-sample-application-to-work-with-your-azure-sphere-tenant-and-devices), could you add a picture to show what a correct app_manifest.json will be? Now our bootcamp material is referring to this page for default Azure sphere template setup, many attendees do not know how to set it correctly. And there is no word to mention that user need fill scopeID to CmdArgs key. 

I used to use this picture, or something similar
![central_manifest](https://user-images.githubusercontent.com/20612136/84644485-d03ae380-af31-11ea-8794-b1543dcde73c.png)

**Comment by johnnyhli** [comment]
Hi @xiongyu0523 - Thanks for bring this up! We will look into it. 

I think the ShowIoTCentralConfig program could also help you with this issue. If you followed [Configure the sample application...](https://github.com/Azure/azure-sphere-samples/blob/master/Samples/AzureIoT/IoTCentral.md#configure-the-sample-application-to-work-with-your-azure-sphere-tenant-and-devices) , the ShowIoTCentralConfig program will generate a configuration code like this:

```
Find and modify the CmdArgs, AllowedConnections and DeviceAuthentication lines in your app_manifest.json so each includes the content from the below:
"CmdArgs": [ "0ne0xxxxxx" ],
"Capabilities": {
    "AllowedConnections": [ "global.azure-devices-provisioning.net", "iotc-xxxx.azure-devices.net" ],
    "DeviceAuthentication": "--- YOUR AZURE SPHERE TENANT ID---",
}

Obtain your Azure Sphere Tenant ID by opening an Azure Sphere Developer Command Prompt/Terminal and typing the following command:

'azsphere tenant show-selected'
```

Will this configuration code help? 

Thanks,
Johnny

**Comment by xiongyu0523** [comment]
Better we can highlight what fields customer need modify . This is the most error prone area.
