### ISSUE TITLE
Need a human readable Device ID

### ISSUE THREAD

**Issue by mesgar** [Azure/azure-sphere-samples#145]
Hi,

We're using Sphere and Azure IoT Hub.
IoT Hub device id is 128 characters long and its not human readable.

`azsphere device show-attached`
`Device ID: E78A07E178D315149231A9E35FFB2CD085F3185EB5B47CA0527E93AACDE983116FDF0C1F0EB10A64D637E9360DFE633C23BA0DC946B670299C78F6D46FFE6XXX`

We need a shorter and human readable device id like we did (on azure portal) in good old days.
Any suggestions?

Thanks

**Comment by johnnyhli** [comment]
Hi @mesgar - Thanks for bring this up! Do you mind submit this as a feature request on [User Voice](https://feedback.azure.com/forums/915433-azure-sphere)?

**Comment by mesgar** [comment]
@johnnyhli 

Consider it done.
