### ISSUE TITLE
sphere tenant certificate chain has varying key parameters for ECDSA

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-sphere-samples#155]
During testing mutual authentication [[1](https://github.com/Azure/azure-sphere-samples/blob/d03ed2c8dad75cfa7b7e4c0b78e85f81a3b5f44c/Samples/HTTPS/HTTPS_Curl_Easy/README.md#using-the-sample-with-mutual-authentication)], my https server was not able to validate the azure sphere client certificate. I tried to validate the leaf certificate (received in https server application) with tenant certificate chain as root ca and it failed. 
```console
$ azsphere tenant download-ca-certificate-chain --output CA-cert-chain.p7b
$ openssl pkcs7 -print_certs -inform der -in CA-cert-chain.p7b -out CA-cert-chain.cer
$ openssl verify -verbose -CAfile CA-cert-chain.cer leaf.cer 
C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = Microsoft Azure Sphere 9b831aeb-bbee-408f-b2dc-210e4538c5ad
error 7 at 1 depth lookup: certificate signature failure
error leaf.cer: verification failed
```

It appeared that tenant ca cert had key parameter of `06 08 2A 86 48 CE 3D 03 01 07` while sphere root ca and policy ca had key parameter of `06 05 2B 81 04 00 22`. Is that ok? Attaching tenant certificate chain from avnet mt3620 device running sphere os 20.06.

Attaching leaf and tenant chain as [certs.zip](https://github.com/Azure/azure-sphere-samples/files/4983652/certs.zip).

**Comment by johnnyhli** [comment]
Hi @kiranpradeep - Thanks for asking the question. We are currently looking into it.

**Comment by johnnyhli** [comment]
Hi @kiranpradeep - [20.07 SDK](https://techcommunity.microsoft.com/t5/internet-of-things/azure-sphere-version-20-07-is-now-available/ba-p/1542749)  is now available. Could you download the latest SDK from [here](https://docs.microsoft.com/en-us/azure-sphere/install/install-sdk?pivots=visual-studio#install-the-azure-sphere-sdk) and try the new [azsphere ca-certificate](https://docs.microsoft.com/en-us/azure-sphere/reference/azsphere-ca-certificate) command? Thanks.

**Comment by kiranpradeep** [comment]
No. That did not help. Kindly find below screenshot and [certs](https://github.com/Azure/azure-sphere-samples/files/4998632/certs.zip) used.
![sphere](https://user-images.githubusercontent.com/1491933/88878032-935a5000-d244-11ea-9010-d342526574cf.png)

**Comment by johnnyhli** [comment]
Hi @kiranpradeep - the root cause is the cert is malformed and need to be renewed. [Here ](https://techcommunity.microsoft.com/t5/internet-of-things/known-issue-azure-sphere-tenant-ca-certificate-rotation/ba-p/1557169)is more detail about this issue. The issue will be automatically fixed starting 5th August. But, if you are looking to renew the cert right away, we are happy to help you with it. If you want us to renew the cert now, please sent your Device ID and Tenant ID to AzCommunity@microsoft.com (do not attach it here), with a link back to this issue. Thanks.

**Comment by kiranpradeep** [comment]
Usually when reporting a valid issue to Github projects, the owner of the repository, gives a minimal response in the lines of "Thanks for reporting this issue. I have fixed it commit #xxxxxxx". But here (and in the linked techcommunity article written today) the response was as if, the issue was independently found and fixed. Had that been the case, I would not have been asked to check again after 20.07 release. Not a concern. Just saying :)

**Comment by johnnyhli** [comment]
Hi @kiranpradeep - Thank you for reporting this issue, it really helped us find and fix this issue. With your thorough information, the team was able to target the issue fast. Secondly, I do apologize for bringing more confusion at the beginning here by suggesting you upgrade your SDK.  I misunderstood the root cause for your issue and provided the wrong solution.  Thank you so much for your understanding. Best, Johnny

**Comment by kiranpradeep** [comment]
@johnnyhli I tried today 11/August. The tenant certificate chain validation still fails. Am I doing anything unexpected? 

![cert-chain-invalid](https://user-images.githubusercontent.com/1491933/89886187-d7a50300-dbe9-11ea-9fed-e77ba9636c43.png)

**Comment by iamjohnnyli** [comment]
Hi @kiranpradeep -  Sorry for the inconveniences. From the [article](https://techcommunity.microsoft.com/t5/internet-of-things/known-issue-azure-sphere-tenant-ca-certificate-rotation/ba-p/1557169) I shared, the new certificate will be activated after Aug 18th.

>For tenants that are impacted by this issue, the new and valid tenant CA certificates will be created by August 5, 2020. The new certificates will be activated after August 18, 2020. 

Again, we are happy to help. If you want us to renew the cert now, you can sent your Device ID and Tenant ID  to [AzCommunity@microsoft.com](mailto:AzCommunity@microsoft.com)(do not attach it here), with a link back to this issue.

Thanks,
Johnny

**Comment by kiranpradeep** [comment]
@johnnyhli Thanks for the reply. I was confused for your reply above on 31/Aug.

>Hi @kiranpradeep - the root cause is the cert is malformed and need to be renewed. Here is more detail about this issue. The issue will be automatically fixed starting 5th August. But, if you are looking to renew the cert right away, we are happy to help you with it. If you want us to renew the cert now, please sent your Device ID and Tenant ID to AzCommunity@microsoft.com (do not attach it here), with a link back to this issue. Thanks.
