### ISSUE TITLE
Why AzureIoT sample recreates iothub handle instead of specifying retry policy?

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-sphere-samples#169]
The AzureIoT sample continuously checks if the device is authenticated and then goes on recreate [[1](https://github.com/Azure/azure-sphere-samples/blob/67f0586b0d8ea8d14e237c0696ff4d32b4d775bf/Samples/AzureIoT/main.c#L280)] the iothub handle? Azure-iot-sdk-c samples instead simply specify the retry policy [[2](https://github.com/Azure/azure-iot-sdk-c/blob/2020-07-19/doc/connection_and_messaging_reliability.md#connection-retry-policies)]. That is comparatively easier to read and probably more efficient than recreating the full TCP connection. Why not reuse the handle with retry policy? 

The AzureIoT sample also checks if device is ready [[3](https://github.com/Azure/azure-sphere-samples/blob/67f0586b0d8ea8d14e237c0696ff4d32b4d775bf/Samples/AzureIoT/main.c#L803)] before sending telemetry messages (using maintained state: `iotHubClientAuthenticationState` ). This is also unlike azure-iot-sdk-c samples which simply relies on message confirmation callbacks [[4](https://github.com/Azure/azure-iot-sdk-c/blob/f464326f10cbba497b71c4aa263b6a22e1b375fe/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L58)] to understanding if the message has been published.

Of course, none of these are bugs. But, when the samples take the pain to come up with the above way of writing code, which is even harder to read, the user wonders if that is on purpose and is to cater to any specific scenario. Is this on purpose? If yes, kindly guide us on the purpose.

**Comment by johnnyhli** [comment]
Hi @kiranpradeep - Sorry for the late reply. 

The major reason for the Azure IoT sample using custom reconnect functions is the DAA certificate is valid for only 24 hours, and thus, the sample app needs to go through a full re-provisioning flow with the new certificate at least that often. Therefore, the Azure IoT sample cannot just use the built-in Azure IoT Retry.

The Azure IoT sample check whether device is ready before sending messages for a few reasons:
The callback only fires when the message has been sent over the network or after a substantial timeout. If many messages have been queued for sending while the network is down, it can lead to an out of memory situation. 
The timeout is asynchronous and very long. It's hard to take useful action based on it. It's better to check whether the device can successfully send the messages.

Please let me know if you have other questions. Thanks!
