### ISSUE TITLE
Visual Studio launch.vs.json Error

### ISSUE THREAD

**Issue by Prathik-Bhundary** [Azure/azure-sphere-samples#199]
Hello. I use Avnet Azure Sphere Starter kit Revision 2 Board and I use Visual Studio 2019 Enterprise.
 I have 3 Warnings without any errors. There are my warnings below.
![image](https://user-images.githubusercontent.com/81756111/113294656-e70dc380-9314-11eb-8c53-bc56aa5cbd8f.png)

I have green lines in my launch.vs.json program
![image](https://user-images.githubusercontent.com/81756111/113294904-145a7180-9315-11eb-9321-d337ed308961.png)
 
How can I fix this? Thank You

**Comment by bawilless** [comment]
Which example application are you trying to build?

**Comment by Prathik-Bhundary** [comment]
UART sample High Level Application

**Comment by bawilless** [comment]
I can't reproduce your issue using Visual Studio 2019 V16.9.2.  Make sure . . . 

1. You clone the entire repo: https://github.com/Azure/azure-sphere-samples.git
2. To use the Avnet Starter Kit Rev 2 make sure the CMakeLists.txt file contains the following line:

![image](https://user-images.githubusercontent.com/41625691/113296580-a89de780-92c7-11eb-82d5-0818383a1fb5.png)

When using Visual Studio Code, I often see warnings that go away once I actually do a build.

**Comment by Prathik-Bhundary** [comment]
I too have set the same Target Hardware. And I can build without any problem. It shows Build all succeeded. But when I open the launch.vs.json , it shows this error

**Comment by bawilless** [comment]
Are you running the latest Azure Sphere Visual Studio Extension?

![image](https://user-images.githubusercontent.com/41625691/113297861-27dfeb00-92c9-11eb-8db7-5aff0c217f83.png)

**Comment by bawilless** [comment]
I've also see a fresh CMake Generate Cache operation clean up things like this  . . . .

Right click on CMakeLists.txt and regenerate the cache

![image](https://user-images.githubusercontent.com/41625691/113298237-9b81f800-92c9-11eb-997c-0acfbdedaf6e.png)

**Comment by Prathik-Bhundary** [comment]
![image](https://user-images.githubusercontent.com/81756111/113305623-dbc09500-9320-11eb-800a-36455539af8e.png)

I too clicked the generate option
![image](https://user-images.githubusercontent.com/81756111/113305722-f266ec00-9320-11eb-8370-bfdb87b389ed.png)

Still I have the error

**Comment by bawilless** [comment]
Sorry, I don't think I can be much help at this point.  It seems like this is a tools/configuration issue, since I can't reproduce the issue on my system using the same source project.  I recommend that you post a comment on the Microsoft Q&A site.  Your issue will be seen by more of the Microsoft support staff then here.  The link is: https://docs.microsoft.com/en-us/answers/topics/azure-sphere.html

**Comment by robotdad** [comment]
You may need to delete the cache before regeneration.
![image](https://user-images.githubusercontent.com/1429895/113338791-6f24a680-92de-11eb-8aa5-bdb93ef59c7c.png)

**Comment by Prathik-Bhundary** [comment]
I deleted the cache. Now I have 1 error and 3 warnings
![Uploading image.png…]()

**Comment by Prathik-Bhundary** [comment]
Its not causing any problem while building or debugging. So I will ignore it and continue as it is. I will close this issue. Thank You.
