### ISSUE TITLE
Receive more data on UART High level app

### ISSUE THREAD

**Issue by Prathik-Bhundary** [Azure/azure-sphere-samples#201]
Hello,
I use Avnet Starter kit rev2.
I used the UART High level app sample code provided in this link below.
[https://github.com/Azure/azure-sphere-samples/blob/master/Samples/UART/UART_HighLevelApp/main.c](url)
I removed the sending data part in the code and I'm using only the receiving part. How can I receive varying number of bytes from UART. What changes do I have to make in the sample. 
I have used what @richardtaylorrt has mentioned in this link [https://github.com/MicrosoftDocs/azure-sphere-issues/issues/36](url)  This worked . But how can I use the same function for receiving varying data.
This is my receiving part of the code.
![image](https://user-images.githubusercontent.com/81756111/116506734-805fd380-a8db-11eb-860e-5b9bc0d940d5.png)

Thank you.

**Comment by tokenstar** [comment]
Hi @Prathik-Bhundary .  The answer to your question depends on how you know what the length is. There are many approaches to this, one of which is to encode the length of each message in a message header.  This approach is illustrated in the McuToCloud sample: https://github.com/Azure/azure-sphere-samples/blob/master/Samples/DeviceToCloud/ExternalMcuLowPower/AzureSphere_HighLevelApp/message_protocol.c .  Hope this helps!
