### ISSUE TITLE
Ethernet setup instructions in Azure Sphere version 21.04

### ISSUE THREAD

**Issue by naomitodori** [Azure/azure-sphere-samples#205]
New and changed features in the 21.04 release / Ethernet enabled by default:
https://docs.microsoft.com/en-us/azure-sphere/product-overview/whats-new#ethernet-enabled-by-default

It says that after 21.04 ethernet will automatically be enabled on first reboot after an ethernet board configuration is loaded, so step 6 below unnecessary?

Ethernet setup instructions:
https://github.com/Azure/azure-sphere-samples/blob/master/ethernet-setup-instructions.md

**Comment by tokenstar** [comment]
The ethernet setup instructions are now simplified to account for the automatic enable of ethernet as you mention above. Thanks for the feedback @naomitodori !
