### ISSUE TITLE
Default Interface

### ISSUE THREAD

**Issue by BaillyAlex** [Azure/azure-sphere-samples#238]
Hello,
the build is working as expect, the only issue I have is related to the network interfaces.
I setup and enabled my Wifi interfaces but instead using this one it use the network interface "azspheresvc".
Any solution :) ?

Thank you.

**Comment by chandran-Az** [comment]
Hi @BaillyAlex - Are you using a specific sample for the n/w interface testing? Could you share additional information on how the wifi ids and security details are being configured? Thanks!

**Comment by BaillyAlex** [comment]
Hi @chandran-Az, thank for your reply.
I'm currently using the AzureIOT sample.
About the wifi configuration I follow this step : https://docs.microsoft.com/en-us/azure-sphere/install/configure-wifi?pivots=vs-code

**Comment by BaillyAlex** [comment]
The configuration of my Wifi is currently on **Configuration State enabled** and **ConnectionState Connected**

**Comment by chandran-Az** [comment]
Thanks for the quick update. From a windows powershell, can you run the below command and confirm the connectivity? Ideally, it would show as connected to one of the network connections. below output is for reference.

Command - **azsphere device network list-interfaces**

Output:

![image](https://user-images.githubusercontent.com/64656870/178546049-7f6ac42c-dcb3-40c1-a48d-f84d1ae155d9.png)

**Comment by BaillyAlex** [comment]
here the screenshot.
![image](https://user-images.githubusercontent.com/109076190/178546430-79f12e39-c865-479f-9596-50b6042179dd.png)

**Comment by BaillyAlex** [comment]
and my issue.. :)
![image](https://user-images.githubusercontent.com/109076190/178546758-39679ae0-a785-4c26-89ab-8a5c0b010437.png)

**Comment by chandran-Az** [comment]
Thanks for sharing the screenshots. From the first screenshot, your wifi is configured and connected to Internet with IP 192.168.1.59.
When you sideload an application and attach a debugger, the connection to the device is established through FTDI port and uses the 192.168.35.1 address for the connection. This is a non-issue and just how the product works. Hope this helps.

**Comment by BaillyAlex** [comment]
Do you know how could I use instead wlan0 :) ?

**Comment by BaillyAlex** [comment]
Fixed with : https://docs.microsoft.com/en-us/azure-sphere/app-development/setup-iot-hub?tabs=cliv2beta#step-4-create-an-x509-device-in-your-iot-hub-for-your-azure-sphere-device
