### ISSUE TITLE
Wifi disabled automatically in azure sphere

### ISSUE THREAD

**Issue by nishithvpoojary** [Azure/azure-sphere-samples#269]
Hi. In the Sample [https://github.com/Azure/azure-sphere-samples/tree/main/Samples/WiFi/WiFi_HighLevelApp](url) after adding the wifi and enabling it, if i disconnect the device without doing the remaining functions( i.e., the disable , duplicate and delete ) and connect the device back again.., why does the wifi state shows disabled.
The wifi state stays enabled if i add it through command prompt, but if it is done through code, it becomes disabled automatically. How is it? Thank you.

**Comment by jamesadevine** [comment]
Are you calling [WifiConfig_PersistConfig](https://learn.microsoft.com/en-us/azure-sphere/reference/applibs-reference/applibs-wificonfig/function-wificonfig-persistconfig?view=azure-sphere-legacy) in your code?

**Comment by nishithvpoojary** [comment]
Yes. Is that the function causing this ? Thanks for your reply @jamesadevine

**Comment by jamesadevine** [comment]
Well, I think minimally you need to:

1) Call WifiConfig_AddNetwork 
2) Call the WifiConfig_Set* calls for the network ID returned in 1).
3) Call WifiConfig_SetNetworkEnabled 
4) Call WifiConfig_PersistConfig

Are making all the calls listed above?

**Comment by nishithvpoojary** [comment]
i checked it now.... WifiConfig_PersistConfig was missing inside the WifiNetworkEnableState(void).. Now it is working perfectly. Thanks a lot.

**Comment by jamesadevine** [comment]
Perfect! no problem
