### ISSUE TITLE
Couldn't send data using Private Network Service sample

### ISSUE THREAD

**Issue by nishithvpoojary** [Azure/azure-sphere-samples#271]
Hi, I have been trying the Azure Sphere Private Network Service sample from Github. I have tried using both putty and Command prompt to connect to device. I was using the default eth0.  But got connection error. Please let me know how to fix this. Thank you.
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/0b85c893-c14f-43bf-9620-e018c3cf06da)
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/f0f25542-ed43-4dd3-80d9-3e8f036d43f9)
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/dd86c344-22f7-490e-ab9b-c8359fc8de1b)

**Comment by jamesadevine** [comment]
Either enable eth0 or wlan0, do not have both enabled. Disable one of the network interfaces and update the sample appropriately. Presumably there is an ethernet connection between your PC and the device?

**Comment by nishithvpoojary** [comment]
Thank you for your response @jamesadevine 
If i use "wlan0", application exits as shown in image.
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/7c91668e-ea80-4a88-817b-2207006ed402)

If i use "eth0", and with wifi disabled on device, my PC coonected to same network through wifi, it didn't work.

what did u mean by ethernet connectiion between PC and device?

**Comment by jamesadevine** [comment]
> what did u mean by ethernet connectiion between PC and device?

If you look at the setup section in the [README](https://github.com/Azure/azure-sphere-samples/tree/main/Samples/PrivateNetworkServices#test-the-sample), it says you can either run the app over wifi (wlan0) or ethernet (eth0). By default the application is configured to use ethernet (eth0), there will need to be a direct connection made between the device and PC (look at step 7 in the section linked above).

To test the set up, an [ethernet connection must be made](https://github.com/Azure/azure-sphere-samples/tree/main/Samples/PrivateNetworkServices#test-the-sample) between the device and PC. The commands in this section are run on a PC and communicate to the device over ethernet or wifi.

**Comment by nishithvpoojary** [comment]
I have used eth0 in code and disabled wifi in device. My laptop is connected to Router through wifi and the device is connected to same router through Ethernet. Is this correct?

**Comment by nishithvpoojary** [comment]
<img width="507" alt="image" src="https://github.com/Azure/azure-sphere-samples/assets/45986919/f0674eb9-30ec-41c5-92bc-e602d80d16d5">

I get this error when i try with wlan0... I can use eth0 because my PC doesn't have ethernet port.

**Comment by jamesadevine** [comment]
I would suspect because wlan0 has been assigned an ip address other than the one specified on the [prior line](https://github.com/Azure/azure-sphere-samples/blob/3cd45adae55eb5ac63f12f20f8e1143d1f33887c/Samples/PrivateNetworkServices/main.c#L295). Either adjust the sample to use the IP of the wlan0 interface, or set your router to assign the device the expected IP address from the sample. Otherwise, buy an ethernet to usb adapter and use ethernet!

**Comment by nishithvpoojary** [comment]
I have purchased the ethernet usb adapter, but currently facing device unresponsive error for 5 devices from several days....  
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/5ce13d08-dbda-4412-9a26-3a72e60134af)
I tried recovering the device... Still its not fixed.

**Comment by jamesadevine** [comment]
Hiya,

Please follow this guide: https://learn.microsoft.com/en-us/azure-sphere/install/troubleshoot-installation?view=azure-sphere-integrated&pivots=windows

James
________________________________

**Comment by nishithvpoojary** [comment]
Hi @jamesadevine ...
The device unresponsive error was fixed after i reinstalled the Azure sphere SDK. This unresponsive issue appeared after i set the Ethernet as 192.168.100.10
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/2df0562c-7edb-413b-a67e-f77d56c0c352)

I can only use the sample with 192.168.35.2
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/591a5b3b-966a-49d3-8cc4-8db51b4cf8c6)
 If I change this IP to 192.168.35.3 or 192.168.35.4 in sample, it doesn't work.

**Comment by jamesadevine** [comment]
Hi - do not modify the address of the ethernet "Azure sphere" ethernet adapter. This is created and managed by the Azure Sphere device communication service.

You would need to configure the IP address of the ethernet interface exposed by the usb to ethernet adapter.

Follow [this guide](https://learn.microsoft.com/en-us/azure-sphere/network/configure-ethernet?view=azure-sphere-integrated) to setup azure sphere over ethernet

**Comment by nishithvpoojary** [comment]
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/542392c5-2d41-47b8-8195-8cf2dccb1e05)
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/44829f4c-7557-4b18-a03d-ce52ebdeac6f)
![image](https://github.com/Azure/azure-sphere-samples/assets/45986919/6104209f-15de-4057-8daf-83122af0e9ae)

**Comment by nishithvpoojary** [comment]
The sample works now with 192.168.100.10...
There was a .exe file for my Ethernet-USB adapter that i had to run...
After that the Ethernet adapter media appeared on command prompt while running "ipconfig".

<img width="493" alt="image" src="https://github.com/Azure/azure-sphere-samples/assets/45986919/4ec14b25-8e15-42a8-a1a9-9edc5c7af1ad">

Thanks for the support @jamesadevine
