### ISSUE TITLE
where to find the Edit Template for adding new Measurement

### ISSUE THREAD

**Issue by BillyHsu** [Azure/azure-sphere-samples#47]
Dear Sir,

I follow instruction from the readme of AzureIoT example.
I can't find the edit template from Device Explorer->select your device->device page in "Add new measurements, settings, and properties" segment.
Can you help to check the flow?
Thanks.

Best Regards,
Billy

**Comment by richardtaylorrt** [comment]
Hi - the Azure IoT Central UI has recently changed.  There is now a specific entry for "Device Templates" on the left-hand-side of the UI.  You assign devices to a template using "Device Sets" that are also on the left-hand-side of the UI.  We will update the Azure Sphere docs to reflect this soon.

Please let us know if this doesn't give you enough information to adapt the instructions .

**Comment by richardtaylorrt** [comment]
We're closing this issue now.  Please re-open if you still need assistance, and we'll be happy to help.  Thanks.
