### ISSUE TITLE
target API set must be changed to 2+beta 1905 to build

### ISSUE THREAD

**Issue by ozhernan** [Azure/azure-sphere-samples#59]
in this readme file https://github.com/Azure/azure-sphere-samples/blob/master/Samples/AzureIoT/README.md

The step below to enable ethernet should include a line to ask the user to change the Target API SET property to 2+beta 1905, otherwise it won't build

4.- In main.c, add the following lines before any other networking calls:

 err = Networking_SetInterfaceState("eth0", true);
 if (err < 0) {
       Log_Debug("Error setting interface state %d\n",errno);
       return -1;
   }

**Comment by richardtaylorrt** [comment]
Thanks for raising this.  We'll fix the README as you suggest for this sample, and for other similar samples too.

**Comment by ozhernan** [comment]
Thanks, as you point out,  is not consistent between examples, in the HTTPS example, that extra explanation  is not needed since the right API set is configured in the project.

**Comment by cawhitworth** [comment]
Fixed in #61
