### ISSUE TITLE
remove "" in json capabilities value

### ISSUE THREAD

**Issue by ozhernan** [Azure/azure-sphere-samples#64]
https://github.com/Azure/azure-sphere-samples/tree/master/Samples/HTTPS/HTTPS_Curl_Easy

in step 3, **_Add the following line to the Capabilities section of the app_manifest.json file: "NetworkConfig" : "true"_**

the value is boolean not string, "true" should be true

**Comment by pennyo** [comment]
This has been fixed in the next release of the samples.
