### ISSUE TITLE
You are not signed in or don't have access to the IoT Central App Capabilities.

### ISSUE THREAD

**Issue by EK76** [Azure/azure-sphere-samples#65]
When I run ShowIoTCentralConfig I get this message
You are not signed in or don't have access to the IoT Central App Capabilities.

I have followed the instructions, but I've probably missed something. How do I correct this?

**Comment by richardtaylorrt** [comment]
Hi - have you successfully created an IoT Central Application?  When you run the ShowIoTCentralConfig tool does it prompt you to login?  Are you logging in with the same account you use with IoT Central?  Does the login fail with any other messages?

If this doesn't help, it'd be great if you can share screenshots of what you see in IoT Central and what you see when running the ShowIoTCentralConfig tool.  Thanks.

**Comment by EK76** [comment]
Hi

Thank you for writing to me.
In my opinion, I have successfully created an IoT Central Application. Here are some screenshots.


[cid:7c5cde70-8c5f-43df-92d3-5a63b5fc51fb]
[cid:8fee6116-8d6e-45ff-bf25-79f5b7c7995a]

Do you wan't more screenshots about my  IoT Central Application?

When I run ShowIoTCentralConfig tool it prompts me to login and I a'm using the same account I use with IoT Central.
The login fail only with the message "You are not signed in or don't have access to the IoT Central App Capablitities"

[cid:d755dd97-edec-4212-892e-021433dc00f5]

Do you need more info?

Best regards,
Ken!
________________________________

**Comment by richardtaylorrt** [comment]
Hi - thanks for the reply.  Unfortunately, I don't see the screenshots.  Please can you try adding them directly to this issue on GitHub, rather than replying via email.  Thanks.

**Comment by EK76** [comment]
Hi!

I will do that!

Best regards,
Ken!

________________________________

**Comment by EK76** [comment]
Here is little more info about my issue.
In my opinion I have followed the instruction in the right way. I have created IoT hub and DPS with my live.com account and with the azsphere login commando
I have used the onmicrosoft.com account. Is it done correctly in this way?
![users2](https://user-images.githubusercontent.com/27670926/61213125-cb135a00-a70c-11e9-850f-867b8905e913.jpg)

**Comment by richardtaylorrt** [comment]
Thanks for the extra information.  I think I can see the problem now.  The "live.com" account is a personal account.  It is not a work/school account.  So you should answer "N" to the first question that the tool asks you.

However, the tool isn't able to work automatically with personal accounts.  So instead, you will see that it helps you gather the information you need manually by copy/pasting it from the IoT Central UI.

(Note that when you answered "Y" to the question, I guess the tool checked if you have any IoT Central accounts associated with your "onmicrosoft.com" account.  It correctly answered that there are not any.)

Please let me know if this helps.

**Comment by EK76** [comment]
Now the ShowIoTCentralConfig tool worked for me and I put these values into my app_manifest.json file, 
which can be found in the picture below this text.
![info1](https://user-images.githubusercontent.com/27670926/61221187-9ad5b680-a720-11e9-98a3-05def4f4af84.jpg)
But when I run with Visual Studio it give me the following error.
![info2](https://user-images.githubusercontent.com/27670926/61221217-b17c0d80-a720-11e9-9d7e-62e2447f408f.jpg)
I can’t figure it out what causing this problem?

**Comment by EK76** [comment]
I have set up a working wifi network connection and Azure Sphere has the latest OS version installed.
![info3](https://user-images.githubusercontent.com/27670926/61229266-8dc0c380-a730-11e9-9fef-3c718641c4db.jpg)
Is there anything else I can check?

**Comment by richardtaylorrt** [comment]
Looking at the sample code, one posssibility is that the network isn't "ready" yet.  This only happens when the OS can sucessfully reach an NTP service online to get current time.  So some questions with that in mind:

- Does your network meet [these requirements](https://docs.microsoft.com/en-us/azure-sphere/network/ports-protocols-domains)?
- Does the [HTTPS sample](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/HTTPS/HTTPS_Curl_Easy) work - successfully reading from example.com? 
- Was your device on this network when it updated to 19.06?

**Comment by EK76** [comment]
I tried the HTTPS sample but I get this error message.
![output](https://user-images.githubusercontent.com/27670926/61286462-90bcc200-a7cb-11e9-9e3c-df7ba49dcd5d.jpg)
![ping](https://user-images.githubusercontent.com/27670926/61286496-a205ce80-a7cb-11e9-98f4-66c669e110ba.jpg)
I managed to download the update even if I couldn’t ping to 192.168.0.138, which is Azure Sphere’s 
ip address according to azsphere device show-ota-status
![status](https://user-images.githubusercontent.com/27670926/61286517-afbb5400-a7cb-11e9-90c3-fcb5479a87e3.jpg)
![timeserver](https://user-images.githubusercontent.com/27670926/61286401-6d921280-a7cb-11e9-9e8e-7e58ff44ecc9.jpg)
I’m using for the moment time.sphere.azure.net. I don’t if it is the correct one?
Perhaps I have something wrong with my NTP service?

**Comment by richardtaylorrt** [comment]
Can you try attaching the Azure Sphere device to a different network?  E.g. a mobile hotspot.

Does your network have any restrictions on which devices can connect.  Does it have MAC address filtering, a captive portal, etc?  I.e. a reason why your PC can connect to the internet but your device can't?

It might be an NTP problem in particular, though that's not clear.  I see the requirements also say the network firewall must allow UDP port 123 for NTP.  Does your current network enable this?

Finally, note that the device doesn't respond to pings, so it's expected that these did not work.

**Comment by EK76** [comment]
I tried with the mobile hotspot, same error occurred . I allowed UDP port 123 in my firewall and even disabled firewall but it didn't helped. I have not MAC filtering and captive portal enabled or any other restrictions , that I can think of. I can't understand what I missed or done wrong?

**Comment by richardtaylorrt** [comment]
Hi - sorry that this is proving so difficult.  Please can you

- run `azsphere get-support-data --output diags.zip` with your device attached, soon after repro'ing the issue
- send the zip file to AZCommunity@microsoft.com with a link to this GitHub issue as well as your subscription ID.

This will allow us to get a support ticket opened for this issue.

**Comment by floresboy** [comment]
same issue here
any news on this ?

**Comment by richardtaylorrt** [comment]
Hi - @floresboy, this GitHub issue ended up covering multiple different potential problems.  Please could you clarify precisely what you are seeing.
- If it's an issue with running a specific sample app, then please raise a new issue in this repo.
- If it's a general issue in getting started with Azure Sphere, please raise it on our [MSDN forum ](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azuresphere) where our community can help.

Thanks.

**Comment by richardtaylorrt** [comment]
We're closing this issue now.  Please re-open here, or on the MSDN forum (as above) if you still need assistance, and we'll be happy to help.  Thanks.
