### ISSUE TITLE
Using I2C in an RT capable application

### ISSUE THREAD

**Issue by KomalBagai** [Azure/azure-sphere-samples#73]
How can we use I2C in a RT app using the M4 subsystems without using a High level application?
An RT app is provided for UART but not for I2C or SPI.

**Comment by richardtaylorrt** [comment]
Unfortuantely, a sample RT app for I2C isn't yet available.  We’re working with Mediatek to get to this, and ship official RTapp drivers/samples for all the MT3620 peripherals.

You could try to write it from scratch, based on the datasheet (available from Azure.Sphere@avnet.com) but that wouldn't be straightforward.  Or depending on your application, , you can prototype using the [High-Level sample I2C app](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/I2C), and move to a RT app later.

**Comment by KomalBagai** [comment]
Thanks.
