### ISSUE TITLE
C# support example

### ISSUE THREAD

**Issue by softlion** [Azure/azure-sphere-samples#78]
Is the board capable of using C# code, maybe transformed to a lower level language using LLVM, like Xamarin is able to do for iOS and Android ?

**Comment by richardtaylorrt** [comment]
Hi - we don't have any support for this today.  Please could you show your backing for this idea [here](https://feedback.azure.com/forums/915433-azure-sphere/suggestions/35781661-support-c-c), by upvoting and maybe commenting about the value it would bring you.  Thanks.

**Comment by softlion** [comment]
This is the shittest answer i ever received.
