### ISSUE TITLE
Headers for CPP

### ISSUE THREAD

**Issue by Wiz-IO** [Azure/azure-sphere-samples#82]
Please correct "system" header files for C++ compatible 

`
#ifdef __cplusplus
extern "C"
{
#endif

...................

#ifdef __cplusplus
}
#endif
`

**Comment by richardtaylorrt** [comment]
Thanks for the suggestion.  We've added it to our backlog for consideration.  For now, we don't currently support C++ on Azure Sphere.

**Comment by Wiz-IO** [comment]
https://github.com/Wiz-IO/framework-azure/blob/master/Sysroots/2%2BBeta1905/linker_cpp.ld

**Comment by Jeff-Schafer** [comment]
We're closing this issue now. Please re-open if you still need assistance, and we'll be happy to help. Thanks.
