### ISSUE TITLE
I2C app has wrong whoami value

### ISSUE THREAD

**Issue by fmuntean** [Azure/azure-sphere-samples#91]
I2C accelerometer application starting.
INFO: WHO_AM_I=0x6c (I2CMaster_WriteThenRead)
ERROR: Unexpected WHO_AM_I value.
Closing file descriptors.
Application exiting.

Once I change the code to accept this value it works.
I found the datasheet for the IC: https://www.st.com/resource/en/datasheet/lsm6dso.pdf
Check page 49 where it says that is hardcoded as 0x6C

I also found the board schematic here: http://cloudconnectkits.org/sites/default/files/AES-MS-MT3620-SK-G_SCH_2019-03-06.PDF

would be also good to have these linked in the documentation for these samples.

**Comment by richardtaylorrt** [comment]
Hi - there is a slightly confusing coincidence here:
- The Azure Sphere [I2C sample app](https://github.com/Azure/azure-sphere-samples/tree/master/Samples/I2C) happens to use the LSM6DS**3**.
- The Avnet Starter Kit (note there are other Azure Sphere dev kits) happens to have an on-board LSM6DS**0**.

These two chips have different registers etc, so the DS3 sample app won't work against the onboard DS0.  There are two options:
1. Run the sample app unchanged against an external DS3, following the wiring instructions you found above.
2. Alter the sample app to run against the DS0 on ISU1.  As you've discovered, you'd need to change the code and app_manifest.json accordingly.
Hope this helps.

**Comment by fmuntean** [comment]
Thank you.
would be good to have these instructions in the sample code so others do not run into the same issue.
