### ISSUE TITLE
Linux kernel Source code

### ISSUE THREAD

**Issue by fmuntean** [Azure/azure-sphere-samples#93]
Where is the Linux kernel source code used by the Azure Sphere board?

I can only see the headers files and object files in the SDK directory.

**Comment by richardtaylorrt** [comment]
Hi - please take a look at [Third party disclosures and source code](https://3rdpartysource.microsoft.com/), and filter on 'Azure Sphere', where you can download this source.

**Comment by fmuntean** [comment]
Thank You.
