### ISSUE TITLE
How do we get the wlan0 IP address ?

### ISSUE THREAD

**Issue by fmuntean** [Azure/azure-sphere-samples#97]
it seems that ioctl is not currently implemented.
How can we get the current IP address for the wireless when in DHCP mode ?

**Comment by richardtaylorrt** [comment]
Have you tried using [getifaddrs()](http://man7.org/linux/man-pages/man3/getifaddrs.3.html)?  (Note: I've not had a chance to test this myself.)

**Comment by fmuntean** [comment]
Thank You, This worked.
