### ISSUE TITLE
API to wire GPIO interrupts

### ISSUE THREAD

**Issue by fmuntean** [Azure/azure-sphere-samples#98]
Hi,
Can you provide info on how to setup a GPIO input as an interrupt please?

**Comment by richardtaylorrt** [comment]
Hi – unfortunately, this isn’t possible with the current OS software.  We are tracking this work on our backlog.  (But it’s not quite as simple as it might seem.)  Please do add this request to our [UserVoice ](https://feedback.azure.com/forums/915433-azure-sphere) too.
